config/routes.rb
TodoList::Application.routes.draw do

  devise_for :users

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  resources :projects, except: [:show] do
    resources :lists,  except: [:show]
  end

  resources :lists, except: [:show] do
    resources :tasks, except: [:show] do
      member do
         get 'change_state'
      end
    end
  end

  resources :sessions, only: [:create]
  match '/lists/:list_id/tasks/:state' => 'tasks#index', state: /(done|in_work)/
  match '/projects/:project_id/members' => 'project_memberships#index', as: "members_project"
  get  '/projects/:project_id/members/invite' => 'project_memberships#new', as: "invite_project"
  post   '/projects/:project_id/members/invite' => 'project_memberships#create', as: "invite_the_user_project"
  delete   '/projects/:project_id/members/:id' => 'project_memberships#destroy', as: "destroy_members_project"
  root :to => 'pages#home'

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to  :user

  has_many :lists, dependent:  :destroy
  has_many :project_memberships
  has_many  :members, through: :project_memberships

  validates :name, presence: true

  def invite_user(member)
    UserMailer.invite(member,self.name).deliver
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  # GET /projects/new
  # GET /projects/new.json
  def new
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.own_projects
    @projects_invited_in = current_user.projects
    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    redirect_to lists_path

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end
  # GET /projects/1/edit
  def edit
  end
  # POST /projects
  # POST /projects.json
  def create
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project/1
  # PUT /project/1.json
   def update
     respond_to do |format|
        if @project.update_attributes(params[:project])
          format.html { redirect_to @project, notice: 'Project was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
   end
  # DELETE /project/1
  # DELETE /project/1.json
   def destroy
     if @project.destroy
      flash[:success] = 'Project was successfully destroyed'
     else
      flash[:error] = "Project wasn't destroyed"
     end
     redirect_to projects_path
     respond_to do |format|
       format.html { redirect_to projects_url }
       format.json { head :no_content }
     end
   end


  end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/_erb/projects/_form.erb
<%= form_for([@user,@project]) do |f| %>
     <%= render 'shared/error_messages', :object => f.object %>
     <div class="field">
         <%= f.label :name %> <br />
         <%= f.text_field :name %>
     </div>

     <div class="field">
         <%= f.label :description %> <br />
         <%= f.text_area :description %>
     </div>

     <div class="actions">
         <%= f.submit @button_name %>
     </div>
<% end %>

app/views/_erb/projects/edit.html.erb
<h1>Editing <%= @project.name %> </h1>
    <%= render 'form' %>

app/views/_erb/projects/index.html.erb
<div class="content">
    <% if @projects.blank? %>
        <p> There is no project. </p><br />
        <p>Do you want to   <%=  link_to "Add", new_project_path%> new one?</p>
    <% else %>
        <table>
            <tr>
                <td><%=  link_to "User lists", lists_path %></td>
            </tr>
            <tr></tr>
            <% @projects.each do |project|           %>
            <tr>
            <td><%=  link_to project.name, project_lists_path(project) %></td>
            <td><%=  project.description %></td>
            <td><%=  link_to "Edit", edit_project_path( project)%></td>
            <td><%=  link_to "Delete", [project], confirm: 'Are you sure?', method: :delete %></td>
              <td><%=  link_to "Members", project_path(project)+'/members' %></td>
            </tr>
    <% end %>
    </table>
        <p>Do you want to   <%=  link_to "Add", new_project_path%> new one?</p>
    <% end %>
</div>

app/views/_erb/projects/new.html.erb
<div class="content">
    <h1>Adding new project</h1>
    <%= render 'form' %>
</div>