config/routes.rb
TodoList::Application.routes.draw do

  devise_for :users

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  resources :projects, except: [:show] do
    resources :lists,  except: [:show]
  end

  resources :lists, except: [:show] do
    resources :tasks, except: [:show] do
      member do
         get 'change_state'
      end
    end
  end

  resources :sessions, only: [:create]
  match '/lists/:list_id/tasks/:state' => 'tasks#index', state: /(done|in_work)/
  match '/projects/:project_id/members' => 'project_memberships#index', as: "members_project"
  get  '/projects/:project_id/members/invite' => 'project_memberships#new', as: "invite_project"
  post   '/projects/:project_id/members/invite' => 'project_memberships#create', as: "invite_the_user_project"
  delete   '/projects/:project_id/members/:id' => 'project_memberships#destroy', as: "destroy_members_project"
  root :to => 'pages#home'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  belongs_to :executor, class_name: 'User'
  belongs_to :user
  validates :name, presence: true

  before_create do
   list = List.find_by_id(self.list_id)
   self.executor_id ||= list.user_id
  end

  state_machine :state, initial: :in_work  do
     state :in_work
     state :done

    event :change_state do
      transition in_work: :done,  do: :send_email_to
      transition done: :in_work, do: :send_email_to
    end
  end

  def send_email_to(user)
    if self.executor_id != user.id
      user = User.find_by_id(self.executor_id)
      UserMailer.assignment(user, self).deliver
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource :list
  load_and_authorize_resource :task, through: :list

  def index
    params[:state]? @tasks = @list.tasks.where("state = ?", params[:state]) : @tasks = @list.tasks
    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @tasks }
    end
  end

  def new
    @project = @list.project
    @members=@project.members if @project

  end

  def create
    #@task.send_email_to(current_user)
      respond_to do  |format|
        if @task.save
          format.html { redirect_to list_tasks_path(@list), success: 'Task was successfully created' }
          format.json { render json: @task, status: :created, location: [@list, @task] }
        else
          format.html { render action: "new", error: "Task wasn't created" }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update_attributes(params[:task])
        #@task.send_email_to(@task.executor)
        format.html { redirect_to  list_tasks_path(@list), success: 'Task was successfully updated' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" , error: "Task wasn't updated"}
        format.json { render json: @task.errors,  status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy ? flash[:success] = "Task was destroyed" : flash[:error] = "Task wasn't destroyed"
    redirect_to list_tasks_path(@task.list)
  end

  def change_state
    @task.change_state
    if @task.update_attributes(params[:task])
      flash[:success] = 'State was changed successfully'
    else
      flash[:error] = "State wasn't changed"
    end
    redirect_to list_tasks_path(@list)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/_erb/tasks/_form.html.erb
<%= form_for([ @list,@task]) do |f| %>

    <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
        <%= f.label :name %> <br />
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :description %> <br />
        <%= f.text_field :description %>
    </div>

   <div class="field">
       <%= f.label :state %> <br />
       <%= f.check_box :state,{}, "Done", "In work" %>
  </div>

   <div class="field">
       <%= f.label :priority %> <br />
       <%= f.select :priority, 1..5 %>
  </div>

  <% if !@members.nil? %>
    <div class="field">
      <%= f.label :executor_id %> <br />
      <%= f.select :executor_id, options_from_collection_for_select(@members,'id','name') %>
    </div>
  <% end %>

  <div class="actions">
      <%= f.submit @button_name %>
  </div>
 <% end %>

app/views/_erb/tasks/edit.html.erb
<div class="content">
    <h1>Editing <%= @task.name %></h1>
    <%= render 'form' %>
</div>

app/views/_erb/tasks/index.html.erb
<div class="content">

    <% if !(@project.nil?)  %>
          <p><span class="project_name"> <%= link_to @project.name, projects_path  %></span>  </p>
    <%end%>

    <p class="list_name"><%=  @list.name%></p>

    <ul class="task_state">
        <li> <%= link_to "Done ",  list_tasks_url(@list)+'/done' %> </li>
        <li><%= link_to "In work ",  list_tasks_url(@list)+'/in_work' %></li>
        <li><%= link_to "Show all ",  list_tasks_url(@list) %></li>
    </ul>

    <table>
        <% @tasks.each do |task| %>
            <tr class=<%= task.state == "Done" ? 'done' : 'in_work' %>>
               <td><b> <%= task.name  %> </b> </td>
               <td><%= task.description  %></td>
               <td><%= task.priority %></td>
               <td><%= task.executor.name if !task.executor.nil? %></td>
               <td><%= link_to task.state, change_state_list_task_url(@list,task)%></td>
            </tr>
            <tr>
               <td><%= link_to "Edit", edit_list_task_path(@list,task) %></td>
               <td><%= link_to "Delete",[ @list, task] , confirm: 'Are you sure?', method: :delete %></td>
            </tr>
        <% end %>
    </table>

    <%= link_to "Add the task", new_list_task_path(@list) %>
</div>

app/views/_erb/tasks/new.html.erb
<div class="content">
    <h1>Adding new task</h1>
    <%= render 'form' %>
</div>