config/routes.rb
TodoList::Application.routes.draw do

  devise_for :users

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  resources :projects, except: [:show] do
    resources :lists,  except: [:show]
  end

  resources :lists, except: [:show] do
    resources :tasks, except: [:show] do
      member do
         get 'change_state'
      end
    end
  end

  resources :sessions, only: [:create]
  match '/lists/:list_id/tasks/:state' => 'tasks#index', state: /(done|in_work)/
  match '/projects/:project_id/members' => 'project_memberships#index', as: "members_project"
  get  '/projects/:project_id/members/invite' => 'project_memberships#new', as: "invite_project"
  post   '/projects/:project_id/members/invite' => 'project_memberships#create', as: "invite_the_user_project"
  delete   '/projects/:project_id/members/:id' => 'project_memberships#destroy', as: "destroy_members_project"
  root :to => 'pages#home'

end

app/views/_erb/shared/_error_messages.html.erb
<% if object.errors.any? %>
 <div id = "error_explanation">
     <h2>
         <%= pluralize(object.errors.count, "error") %>
         prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
     </h2>
     <p>There were problems with the following fields:</p>
         <ul>
             <% object.errors.full_messages.each do |msg| %>
                  <li> <%= msg %></li>
             <% end %>
         </ul>
 </div>
<% end %>

app/views/_erb/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="sidebar">
    <a href="<%= following_user_path(@user) %>">
        <%= @user.following.count %> following
    </a>
    <a href="<%= followers_user_path(@user) %>">
        <%= pluralize(@user.followers.count, "follower") %>
    </a>
</div>

app/views/_erb/shared/_user_info.html.erb
<div class = "sidebar">
    <%= gravatar_for current_user, :size => 50 %>
    <span class= "user_name"><%= link_to current_user.name,user_path(current_user) %> <br/>  </span>
    <%= link_to  pluralize(current_user.projects.count,"Project"), projects_path%>  <br />
    <%= link_to  pluralize(current_user.lists.count,"List"), lists_path %> <br />
   <p><%=  "I should done " + pluralize( current_user.tasks.count,"task") %></p>
</div>