config/routes.rb
TodoList::Application.routes.draw do

  devise_for :users

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  resources :projects, except: [:show] do
    resources :lists,  except: [:show]
  end

  resources :lists, except: [:show] do
    resources :tasks, except: [:show] do
      member do
         get 'change_state'
      end
    end
  end

  resources :sessions, only: [:create]
  match '/lists/:list_id/tasks/:state' => 'tasks#index', state: /(done|in_work)/
  match '/projects/:project_id/members' => 'project_memberships#index', as: "members_project"
  get  '/projects/:project_id/members/invite' => 'project_memberships#new', as: "invite_project"
  post   '/projects/:project_id/members/invite' => 'project_memberships#create', as: "invite_the_user_project"
  delete   '/projects/:project_id/members/:id' => 'project_memberships#destroy', as: "destroy_members_project"
  root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  has_many :project_memberships, foreign_key: 'member_id'
  has_many :projects, through: :project_memberships

  has_many :lists,  dependent: :destroy

  has_many :tasks, foreign_key: 'executor_id'
  has_many :tasks

  validates :name, :presence => true,
            :length => {:maximum=>50}

  def member?(project)
    project_memberships.find_by_project_id(project)
  end

  def join!(project)
    project_memberships.create(project_id: project.id)
  end

  def leave!(project)
    project_memberships.find_by_project_id(project).destroy
  end

  def own_projects
    Project.where("user_id = ?", self.id)
  end



end

app/views/_erb/users/_follow.html.erb
<%= form_for current_user.relationships.
                          build(:followed_id => @user.id) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/_erb/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/_erb/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', :object => f.object%>
    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email%>
    </div>

    <div class="field">
        <%= f.label :password %> <br />
        <%= f.password_field  :password%>
    </div>

    <div class="field">
        <%= f.label :password_confirmation, "Confirmation" %><br />
        <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
        <%= f.submit @button_name %>
    </div>
<% end %>

app/views/_erb/users/_unfollow.html.erb
/users/_follow.html.erb

<%= form_for current_user.relationships.
                          build(:followed_id => @user.id) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/_erb/users/edit.html.erb
<div class="content">
<h1>Edit user</h1>

<%= render 'form'%>
<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails" >change</a>
</div>
</div>
  

app/views/_erb/users/index.html.erb
<div class="content">
    <h1>All users</h1>
    <table>
      <% @users.each do |user| %>
        <tr>
          <td >
            <%= gravatar_for user %>
            <%=  link_to user.name, user %>
          </td>
            <% if current_user.admin? %>
              <%=  link_to "Delete", user, confirm: 'Are you sure?', method: :delete,title: "Delete #{user.name}"  %>
            <% end %>
        </tr>
      <% end %>
    </table>
</div>

app/views/_erb/users/new.html.erb
<div class="sign">
<h1>Sign up</h1>
<%= render 'form'%>
</div>

app/views/_erb/users/show.html.erb
<div class ="content">
<h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
 </h1>
  
    <%= render 'follow_form' if signed_in? %>
    <ul>
      <li><%= link_to pluralize(@user.lists.count, "List"), user_lists_path(@user)  %></li>
      <li><%= link_to pluralize(@user.projects.count, "Project"), user_projects_path(@user)   %></li>
    </ul>

</div>